#[build]
#  publish = "public"
#  functions = "netlify/functions"

#[functions."push-lunch"]
#  # Netlify cron uses UTC. 03:00 UTC = 11:00 Asia/Shanghai.
#  schedule = "45 2 * * 1-5"

#[functions."push-supper"]
#  # Netlify cron uses UTC. 09:00 UTC = 17:00 Asia/Shanghai.
#  schedule = "00 8 * * 1-5"
